### ISSUE TITLE
D.inv.mesh hard-coded paths

### ISSUE THREAD

**Issue by robecker** [OHBA-analysis/osl-core#14]
We often have the problem of hard-coded D.inv.mesh paths that become incorrect. As short-term workaround, a little script called osl_relink_Dinv changes all relevant paths to match with the correct ones. Long-term it might be good to think about another, more flexible way to store path info in these fields (relative to main D object etc).

**Comment by RomeshA** [comment]
- Added 'osl_update_inv_dir' in f9aacdd which automatically extracts the old directory
- Documented usage of this function in `osl_example_preprocessing_simple` which will be live shortly

It seems unlikely that there would be an easier solution short of replacing MEEG objects entirely...!
