### ISSUE TITLE
Workbench configuration

### ISSUE THREAD

**Issue by sheljohn** [OHBA-analysis/osl-core#52]
https://github.com/OHBA-analysis/osl-core/blob/c24f40185910d0c519931fab78abedc55fc57a85/util/initialise_workbench.m#L12-L18

The name of the binary folder in Workbench changes depending on the host system.
Currently, the quoted line assumes that the folder for all linux platforms is `bin_linux64`, which is not the case for example when using RedHat (`bin_rh_linux64` instead).
Generally speaking, it is also entirely possible that the host runs a 32 bits system, in which case the name should be `bin_...32` I think?

A simple fix for all these issues could be to configure the path to the Workbench **binary** folder in `osl.conf`; presently, the Workbench path is supposed to point to the root folder instead.

**Comment by jhadida** [comment]
Indirectly fixed in 28b2c7d2b0e76db051bc7cc5acf8f2a366203dca
