### ISSUE TITLE
osl_import - only selected channels 

### ISSUE THREAD

**Issue by zits69** [OHBA-analysis/osl-core#61]
Hi
I have some odd extra channels in my dataset that I don't even want to import, so at osl_import phase of OPT i was wondering if it makes sense to add only select channels for conversion as a possibility?
Or is there a way to specify in the OPT settings?
Thanks :)
zita

**Comment by AJQuinn** [comment]
Hello - sorry for the slow reply. Are you running maxfilter and then converting to SPM within OPT?

Could be tricky to update as the another change to OPT removed the maxfilter+convert settings from the latest version (https://github.com/OHBA-analysis/osl-core/commit/5c84edce09124082f8fc4669bff5eec4302dc42c). The input is now assumed to be a converted SPM file. Can't recall exactly why this was changed, though we normally now recommend running maxfilter outside of OPT. Would only be a couple of lines to add in but probably wouldn't push it to the main branch...

Couple of options, we could change your local version to include a channel selection option (only a couple of lines) or tweak your pipeline to work with the more recent OPT using the channel selection before starting OPT itself. 1 is probably best if you're using the maxfilter options and everything is already working, 2 better if you're just starting this now.

Both workable - let me know!

Cheers

**Comment by zits69** [comment]
Hi!

I got around it by just using SPM itself to convert the fif files, and yes, after maxfilter outside of OPT. I ran with OPT too, without channel selection, to get the file and folder structures...so it seems to work.

I mention it only because in my case, i had 54 extra channels, all MEG, and for some reason they didn't have proper coordinates and they were messing up the coregistration and basically every step after conversion (crashing on the coor2D.m function). 

So thank you for getting back to me, I should be OK for now - but good to know there may be a way to do this in a less messy way!

Also, kind of unrelated: why do we use STI101_down for the trigger rather than STI101_up? I'm sure I knew this at one point but can't remember...

Thanks,
z

**Comment by AJQuinn** [comment]
Ok - sounds like its working. The original spm covert function probably does have the clearest options for channel imports - I think the OSL one was a bit less flexible. You can import by chantype ect but I'm not sure you can specify channels by label atm. 

Not sure about the STI_down opts off the top of my head. I think there is some variabilty in what people are using. I've certainly used up before [(like here)](https://github.com/OHBA-analysis/Quinn2018_TaskHMM/blob/fec03d6a60fb9ca9549e28cabe3f7229ab29dccb/scripts/hmm_1_preprocessing.m#L311). Would depend on how the trigger was send by the stimulus software, probably best to check with the person who collected the data?

Will close this issue now - but can reopen etc if something comes up.

Cheers
